"""MCP prompts: the team-memory workflow, taught by the server itself.

Clients surface these natively (Claude Code: /mcp__tacit__tacit_onboard etc.;
VS Code: the prompt picker), so teammates get the whole workflow from the
endpoint alone — no AGENTS.md editing, no prompt-crafting, no repo clone.
Names carry the tacit_ prefix so it's unmistakable in any client's picker
what the user is invoking. Defined once here; both runtimes render from this
table.

One shared endpoint serves every team project, so each prompt starts by
telling the agent how to pick the right store: infer the project slug from
the repository folder name and pass it on every tool call. Only the agent
knows its working directory — the remote server never does.
"""

from __future__ import annotations

_PROJECT_RULE = (
    "First, determine the project slug: the repository folder name in "
    "kebab-case (e.g. ~/work/Contoso Payments -> contoso-payments; use "
    "`git rev-parse --show-toplevel` if unsure). State which slug you're "
    "using, and pass it as the `project` argument on EVERY memory tool call."
)

# name -> (description, [(arg_name, arg_description, required), ...])
PROMPT_DEFINITIONS: dict[str, tuple[str, list[tuple[str, str, bool]]]] = {
    "tacit_setup": (
        "START HERE. Wire this repo up to team memory: verify the connection, "
        "work out which project's memory applies, and write the standing "
        "instructions so your agent reads and updates memory from now on "
        "without being asked. Run once per repository.",
        [],
    ),
    "tacit_onboard": (
        "Brief me on this project from team memory - run this once when you "
        "start working on an unfamiliar codebase.",
        [],
    ),
    "tacit_recall": (
        "Answer a question from team memory before touching the repo.",
        [("question", "What you want to know.", True)],
    ),
    "tacit_remember": (
        "Distill a learning into a well-formed team memory and store it.",
        [
            ("learning", "The fact/gotcha/decision to store. Leave empty to use "
             "the most recent learning from this conversation.", False),
        ],
    ),
    "tacit_harvest": (
        "End-of-session sweep: find every durable learning from this "
        "conversation that isn't in team memory yet, and store each one.",
        [],
    ),
}

#: Where standing agent instructions live, by client. ``AGENTS.md`` is the
#: cross-tool convention and is written unconditionally; the others are only
#: touched when they already exist, so setup never litters a repo with files
#: for tools the team does not use.
INSTRUCTION_FILES = (
    ("AGENTS.md", "the cross-tool standard - always write this one"),
    ("CLAUDE.md", "Claude Code"),
    (".github/copilot-instructions.md", "GitHub Copilot in VS Code"),
)


def render(name: str, arguments: dict[str, str] | None = None) -> str:
    args = arguments or {}
    if name == "tacit_setup":
        # The instruction block is generated by the same function `tacit
        # install` prints, so the CLI path and the prompt path can never drift
        # into telling two different stories about how to use the memory.
        from .clients import agents_md_snippet

        block = agents_md_snippet("<PROJECT_SLUG>")
        files = "\n".join(f"   - `{path}` - {why}" for path, why in INSTRUCTION_FILES)
        return (
            "Set this repository up to use the team's organizational memory. "
            "Work through these steps and report what you did.\n\n"
            f"1. {_PROJECT_RULE}\n\n"
            "2. Check the connection and see what already exists: call "
            "`memory_list` for this project, then `memory_search` with "
            "scope='org' for one or two of this repo's main technologies. "
            "Report how many memories this project has, and whether other "
            "teams have anything relevant. If everything is empty, say so "
            "plainly - this project is starting its memory from scratch and "
            "you will be the first contributor.\n\n"
            "3. Write the standing instructions into this repo so future "
            "sessions use memory automatically. Insert the block below, "
            "replacing `<PROJECT_SLUG>` with the slug from step 1. Target "
            "files:\n"
            f"{files}\n"
            "   Write `AGENTS.md` always. Only write the other two if they "
            "already exist, and in that case a one-line pointer to AGENTS.md "
            "is enough - do not duplicate the block. If a tacit section is "
            "already present, replace it rather than appending a second copy. "
            "Preserve everything else in the file.\n\n"
            "--- BEGIN BLOCK ---\n"
            f"{block}\n"
            "--- END BLOCK ---\n\n"
            "4. Confirm the loop back to me in three lines: which project slug "
            "you are using, which files you wrote, and the two habits now in "
            "force - search memory before exploring the repo, and store "
            "durable learnings as you work (`tacit_harvest` at the end of a "
            "session is the reliable way to do the second).\n\n"
            "Do not commit anything; leave the changes for the user to review."
        )
    if name == "tacit_onboard":
        return (
            f"I'm starting work on this project. {_PROJECT_RULE}\n"
            "Then brief me from team memory:\n"
            "1. Call memory_brief for the onboarding pack.\n"
            "2. Call memory_list to see what other knowledge exists (gotchas, "
            "architecture, conventions).\n"
            "3. Call memory_search with scope='org' for this project's main "
            "technologies, to surface what OTHER teams have already learned about "
            "them.\n"
            "4. Give me a concise summary: how to set up, the gotchas most "
            "likely to bite me this week, and the conventions my PRs must meet. "
            "Mark anything that came from another team with the project it came "
            "from.\n"
            "If all come back empty, say this project has no team memory yet "
            "and offer to start it with tacit_remember as you work. Do NOT "
            "explore the repository for anything team memory already answers."
        )
    if name == "tacit_recall":
        question = args.get("question", "").strip() or "(ask me for the question)"
        return (
            f"Answer this from team memory FIRST: {question}\n"
            f"{_PROJECT_RULE}\n"
            "Call memory_search with focused keywords (try twice with different "
            "phrasings if the first search misses). Memory is organization-wide: "
            "a hit that carries a `project` field was written by ANOTHER team — "
            "say so when you use it, and treat it as a strong lead rather than "
            "settled fact for this repo. If this project's own memory comes up "
            "empty, search again with scope='org' before giving up; another team "
            "has often hit the same thing. Answer from the returned memories and "
            "cite their paths. Only if memory has nothing relevant, say so "
            "explicitly and then fall back to exploring the repository."
        )
    if name == "tacit_remember":
        learning = args.get("learning", "").strip()
        subject = (
            f"Store this learning in team memory: {learning}"
            if learning
            else "Review this conversation and store the most recent significant "
            "learning (a non-obvious fix, gotcha, decision, or convention) in team memory."
        )
        return (
            f"{subject}\n"
            f"{_PROJECT_RULE}\n"
            "Write it as ONE focused memory:\n"
            "- path: /<category>/<short-slug>.md (categories: onboarding | gotcha | "
            "architecture | convention | general)\n"
            "- content: a '# Title' line that states the fact (search ranks titles "
            "heavily), then 2-6 lines: symptom, root cause, the fix/rule, and any "
            "command or setting verbatim.\n"
            "- tags: 2-4 comma-separated keywords.\n"
            "Memories are readable across the whole organization by default, so "
            "write the title so it makes sense to someone who has never seen this "
            "repo, and name systems explicitly rather than as 'the gateway'. Pass "
            "visibility='team' or 'private' only for unannounced work or "
            "team-internal process notes.\n"
            "First memory_search to check it isn't already stored - if a memory "
            "covers it, memory_read then memory_update it instead of creating a "
            "duplicate. Never store secrets or transient debugging state."
        )
    if name == "tacit_harvest":
        return (
            "Sweep this entire conversation for durable learnings the team should "
            f"keep. {_PROJECT_RULE}\n"
            "For EACH learning (non-obvious fixes, gotchas that cost time, "
            "decisions made, conventions established):\n"
            "1. memory_search to check it isn't already stored.\n"
            "2. If new: memory_create (path /<category>/<slug>.md, '# Title' "
            "heading, 2-6 line body, tags).\n"
            "3. If stale coverage exists: memory_read then memory_update with the "
            "corrected fact.\n"
            "Skip trivia, secrets, and anything derivable by reading the code. "
            "Finish with a one-line-per-memory list of what you stored or updated."
        )
    raise ValueError(f"unknown prompt {name!r}")
